package view;


import java.awt.event.ActionListener;

/**
 *
 * @author jaime
 */
public class ConsoleWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public ConsoleWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextArea();
        BotaoEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotaoAbrirPorta = new javax.swing.JButton();
        BotaoFecharPorta = new javax.swing.JButton();
        BotaoLigarAr = new javax.swing.JButton();
        BotaoDesligarAr = new javax.swing.JButton();
        BotaoTemp1 = new javax.swing.JButton();
        BotaoTemp2 = new javax.swing.JButton();
        BotaoHumidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Console.setColumns(20);
        Console.setRows(5);
        Console.setEnabled(false);
        jScrollPane1.setViewportView(Console);

        BotaoEnviar.setText("Receber");
        BotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEnviarActionPerformed(evt);
            }
        });

        jLabel1.setText("Console");

        BotaoAbrirPorta.setText("Abrir Porta");
        BotaoAbrirPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPortaActionPerformed(evt);
            }
        });

        BotaoFecharPorta.setText("Fechar Porta");
        BotaoFecharPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFecharPortaActionPerformed(evt);
            }
        });

        BotaoLigarAr.setText("Ligar Ar");
        BotaoLigarAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLigarArActionPerformed(evt);
            }
        });

        BotaoDesligarAr.setText("Desligar Ar");
        BotaoDesligarAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDesligarArActionPerformed(evt);
            }
        });

        BotaoTemp1.setText("Temp 1");
        BotaoTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTemp1ActionPerformed(evt);
            }
        });

        BotaoTemp2.setText("Temp 2");
        BotaoTemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTemp2ActionPerformed(evt);
            }
        });

        BotaoHumidade.setText("Humidade");
        BotaoHumidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHumidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(580, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoAbrirPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoFecharPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoLigarAr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoDesligarAr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoHumidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoAbrirPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoFecharPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLigarAr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoDesligarAr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoHumidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoEnviarActionPerformed

    private void BotaoAbrirPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAbrirPortaActionPerformed

    private void BotaoFecharPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFecharPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoFecharPortaActionPerformed

    private void BotaoLigarArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLigarArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLigarArActionPerformed

    private void BotaoDesligarArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDesligarArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoDesligarArActionPerformed

    private void BotaoTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoTemp1ActionPerformed

    private void BotaoTemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTemp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoTemp2ActionPerformed

    private void BotaoHumidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHumidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoHumidadeActionPerformed

    public void addConectarListener(ActionListener listen){
        BotaoEnviar.addActionListener(listen);
    }
    public void addConectarListenerAbrirPorta(ActionListener listen){
        BotaoAbrirPorta.addActionListener(listen);
    }
    public void addConectarListenerFecharPorta(ActionListener listen){
        BotaoFecharPorta.addActionListener(listen);
    }
    public void addConectarListenerLigarAr(ActionListener listen){
        BotaoLigarAr.addActionListener(listen);
    }
    public void addConectarListenerDesligarAr(ActionListener listen){
        BotaoDesligarAr.addActionListener(listen);
    }
    public void addConectarListenerTemp1(ActionListener listen){
        BotaoTemp1.addActionListener(listen);
    }
    public void addConectarListenerTemp2(ActionListener listen){
        BotaoTemp2.addActionListener(listen);
    }
    public void addConectarListenerHumidade(ActionListener listen){
        BotaoHumidade.addActionListener(listen);
    }
    public void AddText(String texto){
        Console.append(texto+"\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAbrirPorta;
    private javax.swing.JButton BotaoDesligarAr;
    private javax.swing.JButton BotaoEnviar;
    private javax.swing.JButton BotaoFecharPorta;
    private javax.swing.JButton BotaoHumidade;
    private javax.swing.JButton BotaoLigarAr;
    private javax.swing.JButton BotaoTemp1;
    private javax.swing.JButton BotaoTemp2;
    private javax.swing.JTextArea Console;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
