/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author jaime
 */
public class SelectDeviceWindow extends javax.swing.JFrame {

    /**
     * Creates new form SelectDeviceWindow
     */
    public SelectDeviceWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pop = new javax.swing.JCheckBox();
        tvu = new javax.swing.JCheckBox();
        veracruz = new javax.swing.JCheckBox();
        cearamirim = new javax.swing.JCheckBox();
        odonto = new javax.swing.JCheckBox();
        museu = new javax.swing.JCheckBox();
        BotaoAtualizar = new javax.swing.JButton();
        ccs = new javax.swing.JCheckBox();
        degepol = new javax.swing.JCheckBox();
        gama = new javax.swing.JCheckBox();
        delta = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dispositivos"));

        pop.setText("Estação PoP");
        pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popActionPerformed(evt);
            }
        });

        tvu.setText("Estação TVU");
        tvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvuActionPerformed(evt);
            }
        });

        veracruz.setText("Estação Vera Cruz");
        veracruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veracruzActionPerformed(evt);
            }
        });

        cearamirim.setText("Estação Ceará Mirirm");
        cearamirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cearamirimActionPerformed(evt);
            }
        });

        odonto.setText("Estação Odonto");
        odonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odontoActionPerformed(evt);
            }
        });

        museu.setText("Estação Museu");
        museu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                museuActionPerformed(evt);
            }
        });

        BotaoAtualizar.setText("Atualizar");

        ccs.setText("Estação CCS");
        ccs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccsActionPerformed(evt);
            }
        });

        degepol.setText("Estação DEGEPOL");
        degepol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degepolActionPerformed(evt);
            }
        });

        gama.setText("Estação Gama");
        gama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamaActionPerformed(evt);
            }
        });

        delta.setText("Estação Delta");
        delta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pop)
                    .addComponent(tvu)
                    .addComponent(veracruz)
                    .addComponent(cearamirim)
                    .addComponent(museu)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BotaoAtualizar)
                        .addComponent(odonto))
                    .addComponent(ccs)
                    .addComponent(degepol)
                    .addComponent(gama)
                    .addComponent(delta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veracruz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cearamirim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odonto)
                .addGap(7, 7, 7)
                .addComponent(museu)
                .addGap(7, 7, 7)
                .addComponent(ccs)
                .addGap(7, 7, 7)
                .addComponent(degepol)
                .addGap(7, 7, 7)
                .addComponent(gama)
                .addGap(7, 7, 7)
                .addComponent(delta)
                .addGap(10, 10, 10)
                .addComponent(BotaoAtualizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popActionPerformed

    private void tvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvuActionPerformed

    private void veracruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veracruzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veracruzActionPerformed

    private void cearamirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cearamirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cearamirimActionPerformed

    private void odontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odontoActionPerformed

    private void museuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_museuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_museuActionPerformed

    private void ccsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccsActionPerformed

    private void degepolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degepolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degepolActionPerformed

    private void gamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gamaActionPerformed

    private void deltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deltaActionPerformed
    public void addConectarListenerAtualizar(ActionListener listen){
        BotaoAtualizar.addActionListener(listen);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BotaoAtualizar;
    protected javax.swing.JCheckBox ccs;
    protected javax.swing.JCheckBox cearamirim;
    protected javax.swing.JCheckBox degepol;
    protected javax.swing.JCheckBox delta;
    protected javax.swing.JCheckBox gama;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JCheckBox museu;
    protected javax.swing.JCheckBox odonto;
    protected javax.swing.JCheckBox pop;
    protected javax.swing.JCheckBox tvu;
    protected javax.swing.JCheckBox veracruz;
    // End of variables declaration//GEN-END:variables
}
